{{- /* Primary ServiceAccount - ALWAYS rendered when serviceAccount.create (FR-010) */ -}}
{{- if (.Values.serviceAccount | default dict).create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-app.serviceAccountName" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml (.Values.serviceAccount | default dict).annotations | nindent 4 }}
  {{- if (.Values.serviceAccount | default dict).automountServiceAccountToken }}
automountServiceAccountToken: {{ (.Values.serviceAccount | default dict).automountServiceAccountToken }}
  {{- end }}
{{- end }}
{{- /* Additional workloads - when workloads map is non-empty (FR-010) */ -}}
{{- if .Values.workloads }}
{{- range $wName, $w := .Values.workloads }}
{{- $sa := $w.serviceAccount | default dict }}
{{- if $sa.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name | default (include "workload.fullname" (dict "ctx" $ "name" $wName)) }}
  labels:
    {{- include "workload.labels" (dict "ctx" $ "name" $wName) | nindent 4 }}
  annotations:
    {{- toYaml ($sa.annotations | default dict) | nindent 4 }}
  {{- if $sa.automountServiceAccountToken }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
