name: QA BOT API env (bot.qa.imsha.by)

on:
  push:
    branches: [ develop]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TARGET: qa
      NEXT_PUBLIC_API_URL: https://api2.imsha.by
      NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
      NEXT_PUBLIC_STRAPI_TOKEN: ${{ secrets.NEXT_PUBLIC_STRAPI_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS v.14.19.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-

      - name: GitHub Action for Yarn install
        run: yarn install

      - name: Github Action for Yarn build
        run: yarn build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: git-to-jelastic
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          config: |
            Host *
              IdentityFile ~/.ssh/git-to-jelastic
              HostkeyAlgorithms +ssh-rsa
              PubkeyAcceptedAlgorithms +ssh-rsa

      - name: Deploy dist with rsync
        run: rsync -avz  --rsh='ssh -o StrictHostKeyChecking=no -i ~/.ssh/git-to-jelastic -p3022' --delete-before dist/ 63835-1897@gate.mycloud.by:~/ROOT/dist

      - name: Deploy node-modules with rsync
        run: rsync -avz  --rsh='ssh -o StrictHostKeyChecking=no -i ~/.ssh/git-to-jelastic -p3022' --delete-before node_modules/ 63835-1897@gate.mycloud.by:~/ROOT/node_modules


      - name: Re-install node_modules & re-start server
        run: |
          ssh -p 3022 -i ~/.ssh/git-to-jelastic -o StrictHostKeyChecking=no -t 63835-1897@gate.mycloud.by "pm2 restart 0 --time"


    # - run: npm run build

#    - run: npm publish -- for creation package


    # - name: List files
    #   run: ls -la
    # - name: Copy to server
    #   run: rsync -avz --delete-before -e "ssh -p 3022 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" dist/ 58336-1897@${{ secrets.SSH_HOST }}:~/ROOT

