name: PROD env (Yandex Cloud)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      TARGET: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      # Runs a single command using the runners shell
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}


      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{secrets.CR_REGISTRY}}
          CR_REPOSITORY: ${{vars.CR_REPOSITORY}}
          IMAGE_TAG: ${{ github.sha }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          docker build -f ./Dockerfile.prod -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
      
      - name: Pulling and starting new image
        env:
          IMAGE_TAG: ${{ github.sha }}
          PORTAINER_URL: ${{ vars.PORTAINER_URL }}
          WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
        run: |
          curl -k -XPOST $PORTAINER_URL/api/webhooks/$WEBHOOK_ID?tag=$IMAGE_TAG
  
  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Export LATEST_TAG
        run: |
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.LATEST_TAG }}
          writeToFile: false
          reverseOrder: true
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
