name: PROD env (imsha.by)

on:
  push:
    # branches: [ all-env-cis ]
    tags:
      - v*
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TARGET: prd
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Create ssh-key file
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com